/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CalendarView;

import CalendarData.DiaryValues;
import is.hi.snorri.transport.Value;
import java.util.Calendar;
import javax.swing.JFrame;

/**
 *
 * @author Ingvi Þór Hermannsson, Háskóli Íslands, ithh5@hi.is
 */
public class CalendarWindow extends javax.swing.JFrame {
    
    
    // Geymir núverandi dagsetningu
    String currentDate;
    // Geymir töflu með viðburðum hverrar dagsetningar
    Value days;
    // Sér um að geyma þá daga sem eiga að vera litaðir
    EventEvaluator v;

    /**
     * Creates new form CalendarWindow
     */
    public CalendarWindow() {
        // Frumstillir vinnsluhluti
        initVinnsla();
        // Frumstillir
        initEventEvaluator();
        // Frumstillir viðmótshluti
        initComponents();
    }
    
    /**
     * Les inn töfluna með viðburðunum og setur currentDate daginn í dag
     */
    private void initVinnsla(){
        days = DiaryValues.loadDays();
        currentDate = DiaryValues.dateToString(Calendar.getInstance().getTime());
    }
    
    /**
     * Sendir days breytuna yfir til VidburdurEvaluator klasans
     */
    private void initEventEvaluator(){
        v = new EventEvaluator();
        v.setVidburdir(days);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorButtons = new javax.swing.ButtonGroup();
        myCalendar = new MyCalendar(v);
        vidburdur = new javax.swing.JTextField();
        vidburdur.setText(DiaryValues.getDateText(days, currentDate));
        greenButton = new javax.swing.JRadioButton();
        redButton = new javax.swing.JRadioButton();
        blueButton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        myCalendar.setPreferredSize(new java.awt.Dimension(780, 434));
        myCalendar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                myCalendarPropertyChange(evt);
            }
        });

        colorButtons.add(greenButton);
        greenButton.setText("Grænn");
        greenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenButtonActionPerformed(evt);
            }
        });

        colorButtons.add(redButton);
        redButton.setText("Rauður");
        redButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redButtonActionPerformed(evt);
            }
        });

        colorButtons.add(blueButton);
        blueButton.setText("Blár");
        blueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueButtonActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                    .addComponent(vidburdur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(greenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(redButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueButton, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {blueButton, greenButton, redButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(myCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vidburdur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(greenButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(redButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blueButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myCalendarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_myCalendarPropertyChange
        
        // Ef viðburði dagsetningar hefur verið breytt
        // er nýi viðburðurinn vistaður í skrá
        if(DiaryValues.setDateText(days, currentDate, vidburdur.getText())){
            saveToFile();
            System.out.println("Nýr atburður hefur verið vistaður");
        }
        
        // Uppfæra currentDate með nýju dagsetningunni
        currentDate = DiaryValues.dateToString(myCalendar.getDate());
        
        getCurrentEvent();
        
        // Uppfæra viðmótið á dagahnöppunum
        myCalendar.getDayChooser().updateUI();
        
        // Uppfæra viðmótið á deginum í dag
        myCalendar.getDayChooser().setDay(myCalendar.getDayChooser().getDay());
        
        System.out.println("Breytt hefur verið um dag");
    }//GEN-LAST:event_myCalendarPropertyChange

    private void redButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redButtonActionPerformed
        
        v.setColor(1);
        // Uppfæra viðmótið á dagahnöppunum
        myCalendar.getDayChooser().updateUI();
        
        // Uppfæra viðmótið á deginum í dag
        myCalendar.getDayChooser().setDay(myCalendar.getDayChooser().getDay());
    }//GEN-LAST:event_redButtonActionPerformed

    private void greenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenButtonActionPerformed
        
        v.setColor(0);
        // Uppfæra viðmótið á dagahnöppunum
        myCalendar.getDayChooser().updateUI();
        
        // Uppfæra viðmótið á deginum í dag
        myCalendar.getDayChooser().setDay(myCalendar.getDayChooser().getDay());
    }//GEN-LAST:event_greenButtonActionPerformed

    private void blueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueButtonActionPerformed
        
        v.setColor(2);
        // Uppfæra viðmótið á dagahnöppunum
        myCalendar.getDayChooser().updateUI();
        
        // Uppfæra viðmótið á deginum í dag
        myCalendar.getDayChooser().setDay(myCalendar.getDayChooser().getDay());
    }//GEN-LAST:event_blueButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EventWindow x = new EventWindow();
        x.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

        /**
     * Nær í viðburð fyrir núverandi dagsetningu og skrifar í vidburdur
     */
    private void getCurrentEvent(){
        
        // Ná í textann sem er geymdur fyrir dagsetninguna currentDate
        String currentEvent = DiaryValues.getDateText(days, currentDate);       
        // Setja textann í textasviðið
        vidburdur.setText(currentEvent);
    }
    
    /**
     * Keyrist þegar forriti er lokað
     * Sér til þess að atburður vistist
     * @param evt 
     */
    private void formWindowClosed(java.awt.event.WindowEvent evt) {                                  
        
        saveToFile();
        System.out.println("Forriti lokað");
    }                                 
    
    
    /**
     * Vistar value töfluna í skrá
     */
    private void saveToFile(){
        try {
            DiaryValues.setDateText(days, currentDate, vidburdur.getText()); 
            DiaryValues.saveDays(days);
        }
        catch(java.io.IOException e){
            System.out.println("There was an error saving your data");
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalendarWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalendarWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalendarWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalendarWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalendarWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton blueButton;
    private javax.swing.ButtonGroup colorButtons;
    private javax.swing.JRadioButton greenButton;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JCalendar myCalendar;
    private javax.swing.JRadioButton redButton;
    private javax.swing.JTextField vidburdur;
    // End of variables declaration//GEN-END:variables
}
